// Initial Seed Data for Organization Management System

export const INITIAL_PERSONNEL = [
  {
    id: 'pers-exec-1',
    name: 'รศ.ดร.ประสิทธิ์ เจริญสุข',
    email: 'prasit.director@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'สำนักงานผู้อำนวยการ',
    position: 'ผู้บริหาร',
    level: 'ชำนาญการพิเศษ',
    appointmentDate: '01-10-2550',
    retirementDate: '30-09-2575',
    status: 'ปกติ',
    role: 'Admin',
    note: 'ผู้อำนวยการสำนักวิทยบริการและเทคโนโลยีสารสนเทศ',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-exec-2',
    name: 'ผศ.ดร.กมลวรรณ ธนสารเจริญ',
    email: 'kamolwan.deputy@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'ฝ่ายบริการวิชาการและส่งเสริมการวิจัย',
    position: 'ผู้บริหาร',
    level: 'ชำนาญการพิเศษ',
    appointmentDate: '01-10-2554',
    retirementDate: '30-09-2579',
    status: 'ปกติ',
    role: 'Admin',
    note: 'รองผู้อำนวยการฝ่ายวิชาการและวิจัย',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-exec-3',
    name: 'ดร.ชาญชัย เกียรติวัฒนา',
    email: 'chanchai.deputy@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'ฝ่ายพัฒนาระบบสารสนเทศ',
    position: 'ผู้บริหาร',
    level: 'ชำนาญการพิเศษ',
    appointmentDate: '01-10-2556',
    retirementDate: '30-09-2582',
    status: 'ปกติ',
    role: 'Admin',
    note: 'รองผู้อำนวยการฝ่ายพัฒนาระบบและโครงสร้างพื้นฐาน',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-exec-4',
    name: 'ผศ.ดร.วิชัย ภัทรเดชากุล',
    email: 'wichai.deputy@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'สำนักงานผู้อำนวยการ',
    position: 'ผู้บริหาร',
    level: 'ชำนาญการพิเศษ',
    appointmentDate: '01-10-2553',
    retirementDate: '30-09-2578',
    status: 'ปกติ',
    role: 'Admin',
    note: 'รองผู้อำนวยการฝ่ายบริหาร',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-hr-1',
    name: 'นางสาวศิริพร บุญช่วย',
    email: process.env.NEXT_PUBLIC_HR_EMAIL || 'tiawongsombat@gmail.com',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'สำนักงานผู้อำนวยการ',
    position: 'บุคลากร',
    level: 'ชำนาญการ',
    appointmentDate: '15-02-2561',
    retirementDate: '30-09-2591',
    status: 'ปกติ',
    role: 'USER',
    note: 'เจ้าหน้าที่บริหารงานบุคคล / งานตรวจสอบเวลาปฏิบัติราชการ',
    avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-9',
    name: 'นางสาวธัญนันท์ กระดาษ',
    email: 'thanyanan@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'ฝ่ายพัฒนาระบบสารสนเทศ',
    position: 'นักวิชาการคอมพิวเตอร์',
    level: 'ปฏิบัติการ',
    appointmentDate: '01-06-2565',
    retirementDate: '30-09-2598',
    status: 'ปกติ',
    role: 'USER',
    note: 'งานพัฒนาระบบบริการเว็บ',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-10',
    name: 'นายกนก บุญพันธ์จันที',
    email: 'kanok@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'ฝ่ายพัฒนาระบบสารสนเทศ',
    position: 'นักวิชาการคอมพิวเตอร์',
    level: 'ชำนาญการ',
    appointmentDate: '01-08-2562',
    retirementDate: '30-09-2592',
    status: 'ปกติ',
    role: 'USER',
    note: 'งานบริหารฐานข้อมูลและระบบสารสนเทศ',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-11',
    name: 'นายวัชร พิชยนันท์',
    email: 'watchara@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'ฝ่ายพัฒนาระบบสารสนเทศ',
    position: 'นักวิชาการคอมพิวเตอร์',
    level: 'ชำนาญการพิเศษ',
    appointmentDate: '01-10-2557',
    retirementDate: '30-09-2585',
    status: 'ปกติ',
    role: 'USER',
    note: 'หัวหน้าฝ่ายพัฒนาระบบสารสนเทศ',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-1',
    name: 'นายสมชาย ใจดี',
    email: 'admin@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'สำนักงานผู้อำนวยการ',
    position: 'เจ้าหน้าที่บริหารงานทั่วไป',
    level: 'ชำนาญการพิเศษ',
    appointmentDate: '01-10-2555',
    retirementDate: '30-09-2580',
    status: 'ปกติ',
    role: 'Admin',
    note: 'หัวหน้าสำนักงานผู้อำนวยการ / ผู้ดูแลระบบหลัก',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-2',
    name: 'น.ส.วนิดา แสงทอง',
    email: 'wanida@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'ฝ่ายพัฒนาระบบสารสนเทศ',
    position: 'นักวิชาการคอมพิวเตอร์',
    level: 'ชำนาญการ',
    appointmentDate: '15-05-2560',
    retirementDate: '30-09-2588',
    status: 'ปกติ',
    role: 'USER',
    note: 'หัวหน้าทีมพัฒนาเว็บแอปพลิเคชัน',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-3',
    name: 'นายอัครเดช มั่นคง',
    email: 'akkaradech@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'ฝ่ายวิศวกรรมระบบเครือข่าย',
    position: 'วิศวกร',
    level: 'ชำนาญการ',
    appointmentDate: '01-08-2558',
    retirementDate: '30-09-2583',
    status: 'ปกติ',
    role: 'USER',
    note: 'ผู้เชี่ยวชาญด้านความปลอดภัยเครือข่าย',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-4',
    name: 'นางสุภาพร ภักดี',
    email: 'supaporn@icit.org',
    personnelType: 'พนักงานพิเศษ',
    department: 'ฝ่ายบริการวิชาการและส่งเสริมการวิจัย',
    position: 'นักวิเคราะห์นโยบายและแผน',
    level: 'ปฏิบัติการ',
    appointmentDate: '03-01-2564',
    retirementDate: '30-09-2592',
    status: 'ปกติ',
    role: 'USER',
    note: 'ประสานงานโครงการวิจัยและบริการวิชาการ',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-5',
    name: 'นายธีระพล อินทนนท์',
    email: 'teerapol@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'ฝ่ายเทคโนโลยีสารสนเทศ วิทยาเขตปราจีนบุรี',
    position: 'นักวิชาการคอมพิวเตอร์',
    level: 'ปฏิบัติการ',
    appointmentDate: '16-09-2562',
    retirementDate: '30-09-2590',
    status: 'ปกติ',
    role: 'USER',
    note: 'ดูแลระบบเครือข่ายวิทยาเขตปราจีนบุรี',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-6',
    name: 'น.ส.กัญญา รัตนพันธ์',
    email: 'kanya@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'ฝ่ายเทคโนโลยีสารสนเทศ วิทยาเขตระยอง',
    position: 'นักวิชาการคอมพิวเตอร์',
    level: 'ชำนาญการ',
    appointmentDate: '01-11-2559',
    retirementDate: '30-09-2586',
    status: 'ปกติ',
    role: 'USER',
    note: 'หัวหน้างานบริการไอซีที วิทยาเขตระยอง',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-7',
    name: 'นายประเสริฐ สุขใจ',
    email: 'prasert@icit.org',
    personnelType: 'พนักงานพิเศษ',
    department: 'สำนักงานผู้อำนวยการ',
    position: 'นักวิชาการพัสดุ',
    level: 'ปฏิบัติการ',
    appointmentDate: '01-02-2565',
    retirementDate: '30-09-2595',
    status: 'ปกติ',
    role: 'USER',
    note: 'งานจัดซื้อจัดจ้างครุภัณฑ์คอมพิวเตอร์',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-8',
    name: 'นายมนัส เก่าดี',
    email: 'manas.retired@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'ฝ่ายพัฒนาระบบสารสนเทศ',
    position: 'นักวิชาการคอมพิวเตอร์',
    level: 'ชำนาญการ',
    appointmentDate: '01-04-2550',
    retirementDate: '30-09-2566',
    status: 'ลาออก',
    role: 'USER',
    note: 'ลาออกไปประกอบธุรกิจส่วนตัว (ตัวอย่างบุคลากรสถานะลาออกสำหรับทดสอบระบบบล็อกการเข้าสู่ระบบ)',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_EXECUTIVES = [
  {
    id: 'exec-1',
    order: 0,
    personnelId: 'pers-exec-1',
    name: 'รศ.ดร.ประสิทธิ์ เจริญสุข',
    position: 'ผู้อำนวยการสำนัก',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'exec-2',
    order: 1,
    personnelId: 'pers-exec-2',
    name: 'ผศ.ดร.กมลวรรณ ธนสารเจริญ',
    position: 'รองผู้อำนวยการฝ่ายวิชาการและวิจัย',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'exec-3',
    order: 2,
    personnelId: 'pers-exec-3',
    name: 'ดร.ชาญชัย เกียรติวัฒนา',
    position: 'รองผู้อำนวยการฝ่ายพัฒนาระบบและโครงสร้างพื้นฐาน',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'exec-4',
    order: 3,
    personnelId: 'pers-exec-4',
    name: 'ผศ.ดร.วิชัย ภัทรเดชากุล',
    position: 'รองผู้อำนวยการฝ่ายบริหาร',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_DEPARTMENTS = [
  {
    id: 'dept-1',
    name: 'สำนักงานผู้อำนวยการ',
    headPersonnelId: 'pers-1',
    supervisingExecutiveId: 'exec-1',
    description: 'บริหารงานทั่วไป นโยบายและแผน การเงิน พัสดุ และการบริหารงานบุคคล',
  },
  {
    id: 'dept-2',
    name: 'ฝ่ายวิศวกรรมระบบเครือข่าย',
    headPersonnelId: 'pers-3',
    supervisingExecutiveId: 'exec-3',
    description: 'ดูแลโครงสร้างพื้นฐานระบบเครือข่าย อินเทอร์เน็ต และความมั่นคงปลอดภัยสารสนเทศ',
  },
  {
    id: 'dept-3',
    name: 'ฝ่ายบริการวิชาการและส่งเสริมการวิจัย',
    headPersonnelId: 'pers-4',
    supervisingExecutiveId: 'exec-2',
    description: 'สนับสนุนการวิจัย พัฒนาศักยภาพบุคลากร และบริการวิชาการสู่สังคม',
  },
  {
    id: 'dept-4',
    name: 'ฝ่ายพัฒนาระบบสารสนเทศ',
    headPersonnelId: 'pers-11',
    supervisingExecutiveId: 'exec-3',
    description: 'ออกแบบและพัฒนาระบบสารสนเทศ ฐานข้อมูล และเว็บแอปพลิเคชันองค์กร',
  },
  {
    id: 'dept-5',
    name: 'ฝ่ายเทคโนโลยีสารสนเทศ วิทยาเขตปราจีนบุรี',
    headPersonnelId: 'pers-5',
    supervisingExecutiveId: 'exec-1',
    description: 'บริการและพัฒนาระบบสารสนเทศประจำวิทยาเขตปราจีนบุรี',
  },
  {
    id: 'dept-6',
    name: 'ฝ่ายเทคโนโลยีสารสนเทศ วิทยาเขตระยอง',
    headPersonnelId: 'pers-6',
    supervisingExecutiveId: 'exec-1',
    description: 'บริการและพัฒนาระบบสารสนเทศประจำวิทยาเขตระยอง',
  },
];

// Initial leaves data is now empty so no dummy leaves are seeded
export const INITIAL_LEAVES = [];

// Seed data for ระบบใบลงเวลา (Time Attendance Requests)
export const INITIAL_TIME_ATTENDANCES = [
  {
    id: 'ta-sample-1',
    requestType: 'ลงเวลากลับปฏิบัติราชการ',
    requesterId: 'pers-9',
    requesterName: 'นางสาวธัญนันท์ กระดาษ',
    requesterEmail: 'thanyanan@icit.org',
    requesterDepartment: 'ฝ่ายพัฒนาระบบสารสนเทศ',
    requesterPosition: 'นักวิชาการคอมพิวเตอร์',
    actionDate: '9/7/2026',
    attendanceDate: '9/4/2026',
    attendanceTime: '6:00:00 PM',
    witnessId: 'pers-10',
    witnessName: 'นายกนก บุญพันธ์จันที',
    witnessEmail: 'kanok@icit.org',
    departmentHeadId: 'pers-11',
    departmentHeadName: 'นายวัชร พิชยนันท์',
    departmentHeadEmail: 'watchara@icit.org',
    deputyDirectorId: 'pers-exec-4',
    deputyDirectorName: 'ผศ.ดร.วิชัย ภัทรเดชากุล',
    deputyDirectorEmail: 'wichai.deputy@icit.org',
    hrOfficerId: 'pers-hr-1',
    hrOfficerName: 'นางสาวศิริพร บุญช่วย',
    hrOfficerEmail: process.env.NEXT_PUBLIC_HR_EMAIL || 'tiawongsombat@gmail.com',
    hrEmail: process.env.NEXT_PUBLIC_HR_EMAIL || 'tiawongsombat@gmail.com',
    imageProofUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=500&auto=format&fit=crop&q=80',
    reason: 'ลืมลงเวลากลับเนื่องจากติดภารกิจประชุมประสานงานระบบเครือข่าย และกลับมาปฏิบัติงานต่อในห้องเซิร์ฟเวอร์จนถึงเวลาดังกล่าว',
    currentStep: 'COMPLETED',
    statusHr: 'ตรวจสอบแล้ว',
    commentHr: 'นางสาวธัญนันท์ ลงเวลามา 07.10 น. และไม่ได้ลงเวลากลับ (นายกนก ลงเวลากลับ 18.00 น.)',
    checkedByHrName: 'นางสาวศิริพร บุญช่วย',
    checkedByHrAt: '2026-09-07T10:30:00.000Z',
    statusWitness: 'รับรอง',
    witnessComment: 'รับรองว่าปฏิบัติงานอยู่ร่วมกันจนถึงเวลาดังกล่าวจริง',
    witnessConfirmedAt: '2026-09-07T11:15:00.000Z',
    statusDeptHead: 'อนุมัติ',
    deptHeadComment: 'อนุมัติการลงเวลาย้อนหลังตามที่พยานได้รับรอง',
    deptHeadApprovedAt: '2026-09-07T14:20:00.000Z',
    statusDeputy: 'อนุมัติ',
    deputyComment: 'อนุมัติเรียบร้อย',
    deputyApprovedAt: '2026-09-07T16:00:00.000Z',
    finalStatus: 'อนุมัติสมบูรณ์',
    activityLog: [
      {
        step: 'CREATE',
        actorName: 'นางสาวธัญนันท์ กระดาษ',
        actorEmail: 'thanyanan@icit.org',
        action: 'ยื่นคำขอลงเวลากลับปฏิบัติราชการ',
        timestamp: '2026-09-07T09:00:00.000Z',
      },
      {
        step: 'HR_REVIEW',
        actorName: 'นางสาวศิริพร บุญช่วย',
        actorEmail: 'siriporn.hr@icit.org',
        action: 'ตรวจสอบแล้ว',
        comment: 'นางสาวธัญนันท์ ลงเวลามา 07.10 น. และไม่ได้ลงเวลากลับ (นายกนก ลงเวลากลับ 18.00 น.)',
        timestamp: '2026-09-07T10:30:00.000Z',
      },
      {
        step: 'WITNESS_CONFIRM',
        actorName: 'นายกนก บุญพันธ์จันที',
        actorEmail: 'kanok@icit.org',
        action: 'รับรองการเป็นพยาน',
        comment: 'รับรองว่าปฏิบัติงานอยู่ร่วมกันจนถึงเวลาดังกล่าวจริง',
        timestamp: '2026-09-07T11:15:00.000Z',
      },
      {
        step: 'DEPT_HEAD_APPROVE',
        actorName: 'นายวัชร พิชยนันท์',
        actorEmail: 'watchara@icit.org',
        action: 'อนุมัติ',
        comment: 'อนุมัติการลงเวลาย้อนหลังตามที่พยานได้รับรอง',
        timestamp: '2026-09-07T14:20:00.000Z',
      },
      {
        step: 'DEPUTY_APPROVE',
        actorName: 'ผศ.ดร.วิชัย ภัทรเดชากุล',
        actorEmail: 'wichai.deputy@icit.org',
        action: 'อนุมัติ (จบกระบวนการ)',
        comment: 'อนุมัติเรียบร้อย',
        timestamp: '2026-09-07T16:00:00.000Z',
      },
    ],
    createdAt: '2026-09-07T09:00:00.000Z',
    updatedAt: '2026-09-07T16:00:00.000Z',
  },
  {
    id: 'ta-sample-2',
    requestType: 'ลงเวลามาปฏิบัติราชการ',
    requesterId: 'pers-2',
    requesterName: 'น.ส.วนิดา แสงทอง',
    requesterEmail: 'wanida@icit.org',
    requesterDepartment: 'ฝ่ายพัฒนาระบบสารสนเทศ',
    requesterPosition: 'นักวิชาการคอมพิวเตอร์',
    actionDate: '9/8/2026',
    attendanceDate: '9/8/2026',
    attendanceTime: '8:25:00 AM',
    witnessId: 'pers-10',
    witnessName: 'นายกนก บุญพันธ์จันที',
    witnessEmail: 'kanok@icit.org',
    departmentHeadId: 'pers-11',
    departmentHeadName: 'นายวัชร พิชยนันท์',
    departmentHeadEmail: 'watchara@icit.org',
    deputyDirectorId: 'pers-exec-4',
    deputyDirectorName: 'ผศ.ดร.วิชัย ภัทรเดชากุล',
    deputyDirectorEmail: 'wichai.deputy@icit.org',
    hrOfficerId: 'pers-hr-1',
    hrOfficerName: 'นางสาวศิริพร บุญช่วย',
    hrOfficerEmail: process.env.NEXT_PUBLIC_HR_EMAIL || 'tiawongsombat@gmail.com',
    hrEmail: process.env.NEXT_PUBLIC_HR_EMAIL || 'tiawongsombat@gmail.com',
    imageProofUrl: '',
    reason: 'เครื่องสแกนลายนิ้วมือขัดข้อง ไม่สามารถบันทึกเวลาได้',
    currentStep: 'WITNESS_CONFIRM',
    statusHr: 'ตรวจสอบแล้ว',
    commentHr: 'ตรวจสอบข้อมูลการเข้าอาคารจากกล้องวงจรปิด พบว่ามาปฏิบัติงานเวลา 08.25 น. จริง',
    checkedByHrName: 'นางสาวศิริพร บุญช่วย',
    checkedByHrAt: '2026-09-08T09:10:00.000Z',
    statusWitness: 'รอรับรอง',
    witnessComment: '',
    statusDeptHead: 'รออนุมัติ',
    statusDeputy: 'รออนุมัติ',
    finalStatus: 'รอดำเนินการ',
    activityLog: [
      {
        step: 'CREATE',
        actorName: 'น.ส.วนิดา แสงทอง',
        actorEmail: 'wanida@icit.org',
        action: 'ยื่นคำขอลงเวลามาปฏิบัติราชการ',
        timestamp: '2026-09-08T08:45:00.000Z',
      },
      {
        step: 'HR_REVIEW',
        actorName: 'นางสาวศิริพร บุญช่วย',
        actorEmail: 'siriporn.hr@icit.org',
        action: 'ตรวจสอบแล้ว',
        comment: 'ตรวจสอบข้อมูลการเข้าอาคารจากกล้องวงจรปิด พบว่ามาปฏิบัติงานเวลา 08.25 น. จริง',
        timestamp: '2026-09-08T09:10:00.000Z',
      },
    ],
    createdAt: '2026-09-08T08:45:00.000Z',
    updatedAt: '2026-09-08T09:10:00.000Z',
  },
  {
    id: 'ta-sample-3',
    requestType: 'ลงเวลากลับปฏิบัติราชการ',
    requesterId: 'pers-7',
    requesterName: 'นายประเสริฐ สุขใจ',
    requesterEmail: 'prasert@icit.org',
    requesterDepartment: 'สำนักงานผู้อำนวยการ',
    requesterPosition: 'นักวิชาการพัสดุ',
    actionDate: '9/8/2026',
    attendanceDate: '9/7/2026',
    attendanceTime: '5:30:00 PM',
    witnessId: 'pers-1',
    witnessName: 'นายสมชาย ใจดี',
    witnessEmail: 'admin@icit.org',
    departmentHeadId: 'pers-1',
    departmentHeadName: 'นายสมชาย ใจดี',
    departmentHeadEmail: 'admin@icit.org',
    deputyDirectorId: 'pers-exec-4',
    deputyDirectorName: 'ผศ.ดร.วิชัย ภัทรเดชากุล',
    deputyDirectorEmail: 'wichai.deputy@icit.org',
    hrOfficerId: 'pers-hr-1',
    hrOfficerName: 'นางสาวศิริพร บุญช่วย',
    hrOfficerEmail: process.env.NEXT_PUBLIC_HR_EMAIL || 'tiawongsombat@gmail.com',
    hrEmail: process.env.NEXT_PUBLIC_HR_EMAIL || 'tiawongsombat@gmail.com',
    imageProofUrl: '',
    reason: 'ลืมลงเวลากลับเนื่องจากจัดเตรียมเอกสารพัสดุและส่งมอบงานเร่งด่วน',
    currentStep: 'HR_REVIEW',
    statusHr: 'รอตรวจสอบ',
    commentHr: '',
    statusWitness: 'รอรับรอง',
    statusDeptHead: 'รออนุมัติ',
    statusDeputy: 'รออนุมัติ',
    finalStatus: 'รอดำเนินการ',
    activityLog: [
      {
        step: 'CREATE',
        actorName: 'นายประเสริฐ สุขใจ',
        actorEmail: 'prasert@icit.org',
        action: 'ยื่นคำขอลงเวลากลับปฏิบัติราชการ',
        timestamp: '2026-09-08T09:20:00.000Z',
      },
    ],
    createdAt: '2026-09-08T09:20:00.000Z',
    updatedAt: '2026-09-08T09:20:00.000Z',
  },
];

