// Initial Seed Data for Organization Management System

export const INITIAL_PERSONNEL = [
  {
    id: 'pers-exec-1',
    name: 'รศ.ดร.ประสิทธิ์ เจริญสุข',
    email: 'prasit.director@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'สำนักงานผู้อำนวยการ',
    position: 'ผู้บริหาร',
    level: 'ชำนาญการพิเศษ',
    appointmentDate: '01-10-2550',
    retirementDate: '30-09-2575',
    status: 'ปกติ',
    role: 'Admin',
    note: 'ผู้อำนวยการสำนักวิทยบริการและเทคโนโลยีสารสนเทศ',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-exec-2',
    name: 'ผศ.ดร.กมลวรรณ ธนสารเจริญ',
    email: 'kamolwan.deputy@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'ฝ่ายบริการวิชาการและส่งเสริมการวิจัย',
    position: 'ผู้บริหาร',
    level: 'ชำนาญการพิเศษ',
    appointmentDate: '01-10-2554',
    retirementDate: '30-09-2579',
    status: 'ปกติ',
    role: 'Admin',
    note: 'รองผู้อำนวยการฝ่ายวิชาการและวิจัย',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-exec-3',
    name: 'ดร.ชาญชัย เกียรติวัฒนา',
    email: 'chanchai.deputy@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'ฝ่ายพัฒนาระบบสารสนเทศ',
    position: 'ผู้บริหาร',
    level: 'ชำนาญการพิเศษ',
    appointmentDate: '01-10-2556',
    retirementDate: '30-09-2582',
    status: 'ปกติ',
    role: 'Admin',
    note: 'รองผู้อำนวยการฝ่ายพัฒนาระบบและโครงสร้างพื้นฐาน',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-1',
    name: 'นายสมชาย ใจดี',
    email: 'admin@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'สำนักงานผู้อำนวยการ',
    position: 'เจ้าหน้าที่บริหารงานทั่วไป',
    level: 'ชำนาญการพิเศษ',
    appointmentDate: '01-10-2555',
    retirementDate: '30-09-2580',
    status: 'ปกติ',
    role: 'Admin',
    note: 'หัวหน้าสำนักงานผู้อำนวยการ / ผู้ดูแลระบบหลัก',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-2',
    name: 'น.ส.วนิดา แสงทอง',
    email: 'wanida@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'ฝ่ายพัฒนาระบบสารสนเทศ',
    position: 'นักวิชาการคอมพิวเตอร์',
    level: 'ชำนาญการ',
    appointmentDate: '15-05-2560',
    retirementDate: '30-09-2588',
    status: 'ปกติ',
    role: 'USER',
    note: 'หัวหน้าทีมพัฒนาเว็บแอปพลิเคชัน',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-3',
    name: 'นายอัครเดช มั่นคง',
    email: 'akkaradech@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'ฝ่ายวิศวกรรมระบบเครือข่าย',
    position: 'วิศวกร',
    level: 'ชำนาญการ',
    appointmentDate: '01-08-2558',
    retirementDate: '30-09-2583',
    status: 'ปกติ',
    role: 'USER',
    note: 'ผู้เชี่ยวชาญด้านความปลอดภัยเครือข่าย',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-4',
    name: 'นางสุภาพร ภักดี',
    email: 'supaporn@icit.org',
    personnelType: 'พนักงานพิเศษ',
    department: 'ฝ่ายบริการวิชาการและส่งเสริมการวิจัย',
    position: 'นักวิเคราะห์นโยบายและแผน',
    level: 'ปฏิบัติการ',
    appointmentDate: '03-01-2564',
    retirementDate: '30-09-2592',
    status: 'ปกติ',
    role: 'USER',
    note: 'ประสานงานโครงการวิจัยและบริการวิชาการ',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-5',
    name: 'นายธีระพล อินทนนท์',
    email: 'teerapol@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'ฝ่ายเทคโนโลยีสารสนเทศ วิทยาเขตปราจีนบุรี',
    position: 'นักวิชาการคอมพิวเตอร์',
    level: 'ปฏิบัติการ',
    appointmentDate: '16-09-2562',
    retirementDate: '30-09-2590',
    status: 'ปกติ',
    role: 'USER',
    note: 'ดูแลระบบเครือข่ายวิทยาเขตปราจีนบุรี',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-6',
    name: 'น.ส.กัญญา รัตนพันธ์',
    email: 'kanya@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'ฝ่ายเทคโนโลยีสารสนเทศ วิทยาเขตระยอง',
    position: 'นักวิชาการคอมพิวเตอร์',
    level: 'ชำนาญการ',
    appointmentDate: '01-11-2559',
    retirementDate: '30-09-2586',
    status: 'ปกติ',
    role: 'USER',
    note: 'หัวหน้างานบริการไอซีที วิทยาเขตระยอง',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-7',
    name: 'นายประเสริฐ สุขใจ',
    email: 'prasert@icit.org',
    personnelType: 'พนักงานพิเศษ',
    department: 'สำนักงานผู้อำนวยการ',
    position: 'นักวิชาการพัสดุ',
    level: 'ปฏิบัติการ',
    appointmentDate: '01-02-2565',
    retirementDate: '30-09-2595',
    status: 'ปกติ',
    role: 'USER',
    note: 'งานจัดซื้อจัดจ้างครุภัณฑ์คอมพิวเตอร์',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'pers-8',
    name: 'นายมนัส เก่าดี',
    email: 'manas.retired@icit.org',
    personnelType: 'พนักงานมหาวิทยาลัย',
    department: 'ฝ่ายพัฒนาระบบสารสนเทศ',
    position: 'นักวิชาการคอมพิวเตอร์',
    level: 'ชำนาญการ',
    appointmentDate: '01-04-2550',
    retirementDate: '30-09-2566',
    status: 'ลาออก',
    role: 'USER',
    note: 'ลาออกไปประกอบธุรกิจส่วนตัว (ตัวอย่างบุคลากรสถานะลาออกสำหรับทดสอบระบบบล็อกการเข้าสู่ระบบ)',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_EXECUTIVES = [
  {
    id: 'exec-1',
    personnelId: 'pers-exec-1',
    name: 'รศ.ดร.ประสิทธิ์ เจริญสุข',
    position: 'ผู้อำนวยการสำนัก',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'exec-2',
    personnelId: 'pers-exec-2',
    name: 'ผศ.ดร.กมลวรรณ ธนสารเจริญ',
    position: 'รองผู้อำนวยการฝ่ายวิชาการและวิจัย',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'exec-3',
    personnelId: 'pers-exec-3',
    name: 'ดร.ชาญชัย เกียรติวัฒนา',
    position: 'รองผู้อำนวยการฝ่ายพัฒนาระบบและโครงสร้างพื้นฐาน',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_DEPARTMENTS = [
  {
    id: 'dept-1',
    name: 'สำนักงานผู้อำนวยการ',
    headPersonnelId: 'pers-1',
    supervisingExecutiveId: 'exec-1',
    description: 'บริหารงานทั่วไป นโยบายและแผน การเงิน พัสดุ และการบริหารงานบุคคล',
  },
  {
    id: 'dept-2',
    name: 'ฝ่ายวิศวกรรมระบบเครือข่าย',
    headPersonnelId: 'pers-3',
    supervisingExecutiveId: 'exec-3',
    description: 'ดูแลโครงสร้างพื้นฐานระบบเครือข่าย อินเทอร์เน็ต และความมั่นคงปลอดภัยสารสนเทศ',
  },
  {
    id: 'dept-3',
    name: 'ฝ่ายบริการวิชาการและส่งเสริมการวิจัย',
    headPersonnelId: 'pers-4',
    supervisingExecutiveId: 'exec-2',
    description: 'สนับสนุนการวิจัย พัฒนาศักยภาพบุคลากร และบริการวิชาการสู่สังคม',
  },
  {
    id: 'dept-4',
    name: 'ฝ่ายพัฒนาระบบสารสนเทศ',
    headPersonnelId: 'pers-2',
    supervisingExecutiveId: 'exec-3',
    description: 'ออกแบบและพัฒนาระบบสารสนเทศ ฐานข้อมูล และเว็บแอปพลิเคชันองค์กร',
  },
  {
    id: 'dept-5',
    name: 'ฝ่ายเทคโนโลยีสารสนเทศ วิทยาเขตปราจีนบุรี',
    headPersonnelId: 'pers-5',
    supervisingExecutiveId: 'exec-1',
    description: 'บริการและพัฒนาระบบสารสนเทศประจำวิทยาเขตปราจีนบุรี',
  },
  {
    id: 'dept-6',
    name: 'ฝ่ายเทคโนโลยีสารสนเทศ วิทยาเขตระยอง',
    headPersonnelId: 'pers-6',
    supervisingExecutiveId: 'exec-1',
    description: 'บริการและพัฒนาระบบสารสนเทศประจำวิทยาเขตระยอง',
  },
];
